// Package embedding provides a unified wrapper interface and client implementations
// for fetching vector embeddings from various AI APIs (e.g. OpenAI, Google Gemini).
package embedding

import (
	"context"
	"errors"
	"fmt"
	"os"
)

// Provider represents the supported AI embedding services.
type Provider string

const (
	// ProviderOpenAI represents OpenAI's API.
	ProviderOpenAI Provider = "openai"
	// ProviderGemini represents Google Gemini's API.
	ProviderGemini Provider = "gemini"
)

// Client is a common interface for vector embedding generation.
// This interface abstracts away the underlying provider details so that
// tasks can run independently of which AI provider is configured.
type Client interface {
	// GetEmbedding converts input text into a vector representation.
	GetEmbedding(ctx context.Context, text string) ([]float32, error)

	// Provider returns the provider name associated with the client.
	Provider() Provider

	// Dimension returns the dimension size of the embedding generated by this client.
	Dimension() int
}

// Config holds the configuration parameters for the embedding client.
type Config struct {
	Provider Provider // Provider name ("openai" or "gemini")
	APIKey   string   // API key (optional: if empty, defaults to environment variables)
	Model    string   // Model name (optional: defaults to standard model for provider)
}

// NewClient is a factory function that constructs and returns the appropriate 
// embedding Client implementation based on the supplied configuration.
func NewClient(cfg Config) (Client, error) {
	switch cfg.Provider {
	case ProviderOpenAI:
		apiKey := cfg.APIKey
		if apiKey == "" {
			apiKey = os.Getenv("OPENAI_API_KEY")
		}
		if apiKey == "" {
			return nil, errors.New("openai API key is required (pass in config or set OPENAI_API_KEY environment variable)")
		}
		model := cfg.Model
		if model == "" {
			model = "text-embedding-3-small" // Default OpenAI model (1536 dimensions)
		}
		return NewOpenAIClient(apiKey, model), nil

	case ProviderGemini:
		apiKey := cfg.APIKey
		if apiKey == "" {
			apiKey = os.Getenv("GEMINI_API_KEY")
		}
		if apiKey == "" {
			return nil, errors.New("gemini API key is required (pass in config or set GEMINI_API_KEY environment variable)")
		}
		model := cfg.Model
		if model == "" {
			model = "text-embedding-004" // Default Gemini model (768 dimensions)
		}
		return NewGeminiClient(apiKey, model), nil

	default:
		return nil, fmt.Errorf("unsupported embedding provider: %s", cfg.Provider)
	}
}
